"use client";
import { useEffect, useMemo, useState, type ReactNode } from "react";

type Column={title:string;field:string;width?:string;render?:(value:any,row:any,rowIndex:number)=>ReactNode;showTooltip?:boolean;tooltipField?:string;renderTooltip?:(row:any,value:any,rowIndex:number)=>ReactNode;hoverFetch?:boolean};
type Action={icon:ReactNode;colorClass?:string;title?:string;onClick:(row:any)=>void;condition?:(row:any)=>boolean};
export type HeaderAction={icon:ReactNode;title?:string;onClick?:()=>void;className?:string;condition?:boolean;children?:HeaderAction[]};
interface Props{data:any[];columns?:Column[];title?:string;totalRecord:number;recordsPerPage?:number;page:number;search?:string;onPageChange?:(n:number)=>void;onSearch?:(t:string)=>void;onSortChange?:(field:string,direction:"asc"|"desc")=>void;onRefresh?:()=>void;onExportExcel?:()=>void;headerActions?:HeaderAction[];actions?:Action[];rowClassName?:(row:any,rowIndex:number)=>string;rowKeyField?:string;onRowMouseEnter?:(e:React.MouseEvent<HTMLElement>,rowKey:any,row:any,rowIndex:number)=>void;onRowMouseLeave?:(e:React.MouseEvent<HTMLElement>,row:any,rowIndex:number)=>void}

function HeaderMenu({action}:{action:HeaderAction}){const[open,setOpen]=useState(false);const items=(action.children||[]).filter(x=>x.condition!==false);return <div className="research-header-menu"><button type="button" className="research-icon-button" title={action.title} onClick={()=>setOpen(v=>!v)}>{action.icon}</button>{open?<div className="research-header-menu-pop">{items.map((x,i)=><button key={`${x.title||i}-${i}`} type="button" onClick={()=>{x.onClick?.();setOpen(false)}}>{x.icon}<span>{x.title}</span></button>)}</div>:null}</div>}

export default function DynamicTable({data,columns=[],title="جدول اطلاعات",totalRecord,recordsPerPage=10,page,search,onPageChange,onSearch,onSortChange,onRefresh,onExportExcel,headerActions=[],actions=[],rowClassName,rowKeyField,onRowMouseEnter,onRowMouseLeave}:Props){
 const[localSearch,setLocalSearch]=useState(search||""); const[sortField,setSortField]=useState(""); const[sortDir,setSortDir]=useState<"asc"|"desc">("asc"); useEffect(()=>setLocalSearch(search||""),[search]); const totalPages=Math.max(1,Math.ceil(totalRecord/recordsPerPage));
 const pages=useMemo(()=>{const arr:number[]=[];for(let i=1;i<=totalPages;i++){if(totalPages<=9||i===1||i===totalPages||Math.abs(i-page)<=2)arr.push(i)}return arr},[totalPages,page]);
 const sort=(field:string)=>{const d=field===sortField&&sortDir==="asc"?"desc":"asc";setSortField(field);setSortDir(d);onSortChange?.(field,d)};
 return <div className="research-table-wrap">
  <div className="research-table-head"><div className="research-table-title">{title}<span>{totalRecord}</span></div><div className="research-search"><input value={localSearch} onChange={e=>{setLocalSearch(e.target.value);onSearch?.(e.target.value)}} placeholder="جستجو..."/><span>⌕</span></div><div className="research-table-actions">{headerActions.filter(a=>a.condition!==false).map((a,i)=>a.children?.length?<HeaderMenu key={`${a.title||i}-${i}`} action={a}/>:<button key={`${a.title||i}-${i}`} type="button" className="research-icon-button" title={a.title} onClick={a.onClick}>{a.icon}</button>)}{onRefresh?<button type="button" className="research-icon-button" onClick={onRefresh} title="تازه‌سازی">↻</button>:null}{onExportExcel?<button type="button" className="research-button" onClick={onExportExcel}>Excel</button>:null}</div></div>
  <div className="research-table-scroll"><table><thead><tr>{columns.map((c,i)=><th key={`${c.field}-${i}`} style={{width:c.width||"auto"}} onClick={()=>sort(c.field)}>{c.title}{sortField===c.field?<small>{sortDir==="asc"?" ↑":" ↓"}</small>:null}</th>)}{actions.length?<th>عملیات</th>:null}</tr></thead><tbody>{data.length?data.map((row,ri)=><tr key={`${rowKeyField?row?.[rowKeyField]??ri:ri}-${ri}`} className={rowClassName?.(row,ri)||""} onClick={()=>actions[0]?.onClick(row)} onMouseLeave={e=>onRowMouseLeave?.(e,row,ri)}>{columns.map((c,ci)=>{const v=row?.[c.field];const content=c.render?c.render(v,row,ri):v;const tip=c.renderTooltip?c.renderTooltip(row,v,ri):c.tooltipField?row?.[c.tooltipField]:undefined;return <td key={`${c.field}-${ci}`} title={typeof tip==="string"?tip:undefined} onMouseEnter={e=>c.hoverFetch&&onRowMouseEnter?.(e,rowKeyField?row?.[rowKeyField]:row,row,ri)}>{content??""}</td>})}{actions.length?<td><div className="research-row-actions">{actions.map((a,ai)=>a.condition&&!a.condition(row)?null:<button key={`${a.title||ai}-${ai}`} type="button" title={a.title} onClick={e=>{e.stopPropagation();a.onClick(row)}}>{a.icon}</button>)}</div></td>:null}</tr>):<tr><td colSpan={columns.length+(actions.length?1:0)} className="research-empty">هیچ داده‌ای یافت نشد</td></tr>}</tbody></table></div>
  <div className="research-pagination"><button type="button" disabled={page<=1} onClick={()=>onPageChange?.(Math.max(1,page-1))}>قبلی</button>{pages.map((n,i)=><span key={`${n}-${i}`}><button type="button" className={n===page?"active":""} onClick={()=>onPageChange?.(n)}>{n}</button>{i<pages.length-1&&pages[i+1]-n>1?<i>…</i>:null}</span>)}<button type="button" disabled={page>=totalPages} onClick={()=>onPageChange?.(Math.min(totalPages,page+1))}>بعدی</button></div>
 </div>
}
